// Pure helpers for the publicist gate and the AGENTS.md sync. No I/O here.

export const START = '<!-- publicist:hard-rules:start (generated by npm run publicist:sync; edit .agents/skills/publicist/SKILL.md instead) -->';
export const END = '<!-- publicist:hard-rules:end -->';

/** The "## Hard rules" section of the canonical skill, without its heading. */
export function hardRules(skill) {
  const match = skill.match(/^## Hard rules[^\n]*\n([\s\S]*?)(?=^## )/m);
  if (!match) throw new Error('canonical skill has no "## Hard rules" section');
  return match[1].trim();
}

/** The block AGENTS.md must contain. */
export function agentsBlock(skill) {
  return `${START}\n## Publicist hard rules\n\nApply these whenever work touches publicist journal entries, \`publicist/\`, or social posts. Full instructions: \`.agents/skills/publicist/SKILL.md\`.\n\n${hardRules(skill)}\n${END}`;
}

/** Insert or replace the generated block. */
export function syncAgents(agents, skill) {
  const block = agentsBlock(skill);
  const start = agents.indexOf(START.slice(0, 40));
  const end = agents.indexOf(END);
  if (start === -1 || end === -1) return `${agents.trimEnd()}\n\n${block}\n`;
  return agents.slice(0, start) + block + agents.slice(end + END.length);
}

/** Entry IDs in a curated project-story data file. */
export function entryIds(source) {
  return [...source.matchAll(/\bid:\s*'([a-z0-9-]+)'/g)].map(m => m[1]);
}

/** Front matter fields of a queued post. */
export function frontMatter(text) {
  const block = text.match(/^---\n([\s\S]*?)\n---/);
  if (!block) return {};
  return Object.fromEntries(block[1].split('\n')
    .map(line => line.replace(/\s+#.*$/, '').match(/^([a-z_]+):\s*(.*)$/))
    .filter(Boolean).map(([, k, v]) => [k, v.trim()]));
}


/**
 * Decide whether a private review note clears the gate.
 * Returns a list of short, content-free reasons; empty means it clears.
 */
export function noteProblems(note) {
  const problems = [];
  const fm = frontMatter(note);
  const tier = fm.tier;
  const refresher = note.match(/^## Refresher\n([\s\S]*?)(?=^## |(?![\s\S]))/m)?.[1] ?? '';
  if (!/^- \*\*/m.test(refresher)) problems.push('refresher missing');
  const review = note.slice(note.search(/^## Owner review/m) >= 0 ? note.search(/^## Owner review/m) : note.length);
  const verified = review.match(/Refresher:\s*(verified|corrected)[ \t]*$/m)?.[1];
  if (!verified) problems.push('refresher not verified');
  const publish = review.match(/Publish:\s*(yes|hold|no)[ \t]*$/m)?.[1];
  if (publish !== 'yes') problems.push('publish is not yes');
  const readiness = review.match(/Whiteboard defense:\s*(ready|not yet|not applicable)[ \t]*$/m)?.[1];
  if (tier === 'shipped' && readiness !== 'ready') problems.push('shipped entry not marked ready');
  else if (tier === 'exploration' && readiness !== 'not applicable') problems.push('exploration entry needs not applicable');
  else if (tier !== 'shipped' && tier !== 'exploration') problems.push('tier missing or invalid');
  return problems;
}

const SECRET = [/\bghp_[A-Za-z0-9]{20,}/, /\bgithub_pat_[A-Za-z0-9_]{20,}/, /\bsk-[A-Za-z0-9]{20,}/, /\bAKIA[0-9A-Z]{16}\b/, /-----BEGIN [A-Z ]*PRIVATE KEY-----/, /\bxox[baprs]-[A-Za-z0-9-]{10,}/];

/** Mechanical text checks for public publicist content. */
export function textProblems(text) {
  const problems = [];
  if (text.includes('\u2014')) problems.push('contains an em dash');
  if (SECRET.some(pattern => pattern.test(text))) problems.push('contains a secret-shaped string');
  return problems;
}

/** Tally captures must be labeled as demo data. */
export function captureProblems(source) {
  const kinds = [...source.matchAll(/'((?:[^'\\]|\\.)*capture(?:[^'\\]|\\.)*)'\s*\)/gi)].map(m => m[1]);
  return kinds.filter(kind => !/demo data/i.test(kind)).map(kind => `capture not labeled demo data: ${kind}`);
}
